### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by andre-schulz**
Hi,
this PR replaces the currently broken Travis CI with GitHub Actions. GitHub Actions is GitHub's own CI infrastructure which is available for free for public repositories, quote from [^1]:
> "GitHub Actions usage is free for standard GitHub-hosted runners in public repositories [...]"

Commits 1 (db7f8028ce5f59e796ddcb5f1148d14e8a484561) to 5 (3eb318d17406e3add3277e56273117487c352130) are fixes/improvements that pave the way for setting up CI via GitHub Actions.

Commit 6 (048e0bba223672d558e686255abad4ffd8ae2380) is the main change which sets up CI via GitHub Actions and includes as many different build environments as possible:
- Ubuntu 20.04, GCC 9.4.0/Clang 10.0.0, x86_64
- Ubuntu 22.04, GCC 11.4.0/Clang 14.0.0, x86_64
- Ubuntu 24.04, GCC 13.2.0/Clang 18.1.3, x86_64
- macOS 12, Clang 14.0.0, x86_64
- macOS 13, Clang 15.0.0, x86_64
- macOS 14, Clang 15.0.0, arm64

Commit 7 (1b693c2d43bf48391c83f2be9a76592d822fd12f) removes the obsolete Travis CI YAML file.

Commits 8 (247ea308f9221c9c88f0950aab19e5d2348aca23) to 11 (1014e8f24195107efc6fab58fad001b46530f767) fix some compiler warnings to reduce noise in the CI logs.

[^1]: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions

### CODE REVIEW

**Comment by andre-schulz** [comment]
When compiling on Ubuntu 20.04 with Clang 10.0.0, the following warning shows up multiple times when compiling unit tests:
```
clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
```
The warning no longer shows up with newer Clang versions, e.g. Ubuntu 22.04 with Clang 14.0.0, so I assume that this is an issue that has been fixed in Clang.

I could modify the build system to detect the specific Clang version to silence the warning but I'm not sure if this is worth the effort because Clang 10.0.0 is rather old and Ubuntu 20.04 standard support ends on April 2025 [^1]. If you want I can look into this or we could fix the issue in a follow-up PR. What do you think?

[^1]: https://ubuntu.com/about/release-cycle

**Comment by andre-schulz** [comment]
When compiling UMVE on Ubuntu 22.04/24.04 with GCC/Clang, the following warning shows up multiple times:
```
  In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:146,
                   from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:49,
                   from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                   from glwidget.h:14,
                   from glwidget.cc:16:
  /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglext.h:60: warning: "GL_GLEXT_VERSION" redefined
     60 | #define GL_GLEXT_VERSION 20190228
        | 
  In file included from /usr/include/GL/gl.h:2050,
                   from ../../libs/ogl/opengl.h:29,
                   from glwidget.cc:14:
  /usr/include/GL/glext.h:35: note: this is the location of the previous definition
     35 | #define GL_GLEXT_VERSION 20220530
        | 
```
The problem is that Qt ships its own `glext.h`, `qopenglext.h` in QtGui, which has a different header guard (`__glext_h_`) than the system `glext.h` (`__gl_glext_h_`).

Judging from [a post in the Qt forum](https://forum.qt.io/topic/121413/qt-definition-of-gl_glext_version-differs-from-open-gl-defintion), It looks like this issue has been present since at least December 2020. Looking at `qopenglext.h` in the official Qt repo, the issue is still present in the [latest 5.15 branch](https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/opengl/qopenglext.h?h=5.15) and the [latest dev branch](https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/opengl/qopenglext.h).

A possible workaround for this could be the following:
```diff
diff --git a/libs/ogl/opengl.h b/libs/ogl/opengl.h
index 397388bd72a5..4fb5d95ea67d 100644
--- a/libs/ogl/opengl.h
+++ b/libs/ogl/opengl.h
@@ -27,7 +27,12 @@
 #else
 #  define GL_GLEXT_PROTOTYPES
 #  include <GL/gl.h>
-#  include <GL/glext.h>
+#  if !defined(QT_OPENGL_LIB) || (defined(QT_OPENGL_LIB) && !defined(__glext_h_))
+#    include <GL/glext.h>
+#    if defined(QT_OPENGL_LIB)
+#      define __glext_h_ 1
+#    endif
+#  endif
 #endif

 #endif /* OGL_OPEN_GL_HEADER */
```
Unfortunately, `QT_OPENGL_LIB` is undocumented but this fixes the warnings. What do you think?

**Comment by simonfuhrmann** [comment]
> When compiling on Ubuntu 20.04 with Clang 10.0.0, the following warning shows up multiple times when compiling unit tests:
> 
> ```
> clang++ -std=c++14 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs `pkg-config --cflags gtest_main`  -c -o math/gtest_algo.o math/gtest_algo.cc
> clang: warning: -lpthread: 'linker' input unused [-Wunused-command-line-argument]
> ```
> 
> The warning no longer shows up with newer Clang versions, e.g. Ubuntu 22.04 with Clang 14.0.0, so I assume that this is an issue that has been fixed in Clang.
> 
> I could modify the build system to detect the specific Clang version to silence the warning but I'm not sure if this is worth the effort because Clang 10.0.0 is rather old and Ubuntu 20.04 standard support ends on April 2025 [1](#user-content-fn-1-549a303137a7983834fddb17e7bd2b54). If you want I can look into this or we could fix the issue in a follow-up PR. What do you think?
> 
> ## Footnotes
> 1. https://ubuntu.com/about/release-cycle [↩](#user-content-fnref-1-549a303137a7983834fddb17e7bd2b54)

Agree, probably not worth the effort.

**Comment by simonfuhrmann** [comment]
> When compiling on macOS 12/13/14 with Clang, the following warning shows up multiple times during compilation of the tests:
> 
> ```
>   clang++ -std=c++14 -pthread -Wall -Wextra -pedantic -Wno-sign-compare -I../libs `pkg-config --cflags gtest_main`  -c -o math/gtest_functions.o math/gtest_functions.cc
>   math/gtest_accum.cc:10:1: warning: use of the 'maybe_unused' attribute is a C++17 extension [-Wc++17-extensions]
>   TEST(AccumTest, TestFloatAccum)
>   ^
>   /usr/local/Cellar/googletest/1.15.2/include/gtest/gtest.h:2192:42: note: expanded from macro 'TEST'
>   #define TEST(test_suite_name, test_name) GTEST_TEST(test_suite_name, test_name)
>                                            ^
>   /usr/local/Cellar/googletest/1.15.2/include/gtest/gtest.h:2186:3: note: expanded from macro 'GTEST_TEST'
>     GTEST_TEST_(test_suite_name, test_name, ::testing::Test, \
>     ^
> ```
> 
> I can also reproduce this on Gentoo Linux with Clang 18.1.8 and GoogleTest 1.15.2.
> 
> It looks like that this is an issue with GoogleTest and how it determines whether a C++ attribute is supported by the compiler and the chosen C++ standard to compile with, see [GoogleTest issue 4605](https://github.com/google/googletest/issues/4605).
> 
> I see two ways to fix this issue:
> 
> 1. Do nothing and just wait it out until GoogleTest fixes the issue.
> 2. Raise the C++ version to C++17 in MVE.
> 
> What do you think?

Let's sit it out. It's just a warning, and only for testing, so not that critical.

**Comment by simonfuhrmann** [comment]
> When compiling UMVE on Ubuntu 22.04/24.04 with GCC/Clang, the following warning shows up multiple times:
> 
> ```
>   In file included from /usr/include/x86_64-linux-gnu/qt5/QtGui/qopengl.h:146,
>                    from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:49,
>                    from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
>                    from glwidget.h:14,
>                    from glwidget.cc:16:
>   /usr/include/x86_64-linux-gnu/qt5/QtGui/qopenglext.h:60: warning: "GL_GLEXT_VERSION" redefined
>      60 | #define GL_GLEXT_VERSION 20190228
>         | 
>   In file included from /usr/include/GL/gl.h:2050,
>                    from ../../libs/ogl/opengl.h:29,
>                    from glwidget.cc:14:
>   /usr/include/GL/glext.h:35: note: this is the location of the previous definition
>      35 | #define GL_GLEXT_VERSION 20220530
>         | 
> ```
> 
> The problem is that Qt ships its own `glext.h`, `qopenglext.h` in QtGui, which has a different header guard (`__glext_h_`) than the system `glext.h` (`__gl_glext_h_`).
> 
> Judging from [a post in the Qt forum](https://forum.qt.io/topic/121413/qt-definition-of-gl_glext_version-differs-from-open-gl-defintion), It looks like this issue has been present since at least December 2020. Looking at `qopenglext.h` in the official Qt repo, the issue is still present in the [latest 5.15 branch](https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/opengl/qopenglext.h?h=5.15) and the [latest dev branch](https://code.qt.io/cgit/qt/qtbase.git/tree/src/gui/opengl/qopenglext.h).
> 
> A possible workaround for this could be the following:
> 
> ```diff
> diff --git a/libs/ogl/opengl.h b/libs/ogl/opengl.h
> index 397388bd72a5..4fb5d95ea67d 100644
> --- a/libs/ogl/opengl.h
> +++ b/libs/ogl/opengl.h
> @@ -27,7 +27,12 @@
>  #else
>  #  define GL_GLEXT_PROTOTYPES
>  #  include <GL/gl.h>
> -#  include <GL/glext.h>
> +#  if !defined(QT_OPENGL_LIB) || (defined(QT_OPENGL_LIB) && !defined(__glext_h_))
> +#    include <GL/glext.h>
> +#    if defined(QT_OPENGL_LIB)
> +#      define __glext_h_ 1
> +#    endif
> +#  endif
>  #endif
> 
>  #endif /* OGL_OPEN_GL_HEADER */
> ```
> 
> Unfortunately, `QT_OPENGL_LIB` is undocumented but this fixes the warnings. What do you think?

I've seen this warning, too. What concerns me a bit is that the versions are different (`20190228` vs `20220530`). I do not know, however, what the impact of this warning is. So I don't mind if we leave the warning, if things work. Not a fan of warnings, but I don't know what to do, haha.

**Comment by simonfuhrmann** [comment]
First of all, thank you Andre, this PR is great! Very much appreciated.

**Comment by simonfuhrmann** [comment]
When clicking on the chip in README.md that points to `https://github.com/simonfuhrmann/mve/actions/workflows/main.yml`, I'll get a 404. Is there a way to make it point to the progress or the last results of the CI?

**Comment by simonfuhrmann** [comment]
> When clicking on the chip in README.md that points to `https://github.com/simonfuhrmann/mve/actions/workflows/main.yml`, I'll get a 404. Is there a way to make it point to the progress or the last results of the CI?

It seems I had to enable Actions the the project repo settings.

**Comment by andre-schulz** [comment]
> > When clicking on the chip in README.md that points to `https://github.com/simonfuhrmann/mve/actions/workflows/main.yml`, I'll get a 404. Is there a way to make it point to the progress or the last results of the CI?
> 
> It seems I had to enable Actions in the project repo settings. Still not sure if things are set up correctly.

Maybe a new commit has to be pushed to master to trigger a CI run? I just noticed a minor issue with one of my commits in this PR. I'll create a PR for the fix and in the PR we'll see whether the CI stuff is setup correctly.

**Pull request merged**
