### PR TITLE
SFM: Improve worst case runtime of track propagation v2

### PR DESCRIPTION
**Pull request by nmoehrle**
I encountered a dataset where the track propagation did not complete after 24 hours. Unifying in the larger of both tracks and effectively reserving the required memory beforehand with insert reduced the runtime to under 15 seconds.

### CODE REVIEW

**Comment by nmoehrle** [comment]
Coffee break discussions...

**Comment by simonfuhrmann** [comment]
I still can't believe that this change reduces time so much. Does this somehow fix an infinite loop bug?

**Comment by nmoehrle** [comment]
I don't think so I was monitoring the process and it did make progress but in a painstakingly slow pace and I don't know which loop would be a candidate. I am happy to provide the prebundle but it has more than 11Gb (> 1400 views).

**Comment by simonfuhrmann** [comment]
Don't worry. Good that his fixes it.

**Pull request merged**
