### PR TITLE
Add OBJ support for UMVE

### PR DESCRIPTION
**Pull request by nmoehrle**
These commits implement OBJ file loading in MVE and add support for textured OBJ files within scene inspect.

### CODE REVIEW

**Comment by simonfuhrmann** [comment]
I like this PR quite a bit. Please fix remaining issues.

**Comment by simonfuhrmann** [comment]
Please also remove the comments `# Vertices` and `# Faces` in the Obj writer, as it pops up when reading meshes.

**Comment by nmoehrle** [comment]
Should all changes be in one patch/commit or should I change the original commits?

**Comment by simonfuhrmann** [comment]
Your call.
Am 24.08.2015 7:23 nachm. schrieb "Nils Moehrle" <notifications@github.com>:

**Comment by nmoehrle** [comment]
On 08/24/2015 09:02 PM, Simon Fuhrmann wrote:
> Your call.
> Am 24.08.2015 7:23 nachm. schrieb "Nils Moehrle"
> <notifications@github.com>:
>
> > Should all changes be in one patch/commit or should I change the
> original
> > commits?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/simonfuhrmann/mve/pull/166#issuecomment-134307279>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/simonfuhrmann/mve/pull/166#issuecomment-134340482>.
>
I used a single commit (#0b1127d) containing all changes and referencing
the pull request. On the one hand to avoid a force push, which might
break the pull request, and on the other hand to enable you to
conveniently review the changes.

**Pull request merged**
