### PR TITLE
UMVE: Improved image viewing

### PR DESCRIPTION
**Pull request by keksberg**
This is an enhancement that improves the handling of image viewing in UMVE (#159)
* Mouse navigation (with left mouse button)
* Zooming with mouse wheel (while keeping the location under the cursor)
* Disable checkability of zoom to fit button
* Use zoom to fit as default when opening a scene

### CODE REVIEW

**Comment by simonfuhrmann** [comment]
Does it work with retina display? Did Fabian test it?

**Comment by flanggut** [comment]
Yes it works. But I'm not a fan of mouse wheel zoom...

**Comment by simonfuhrmann** [comment]
Can we make it, maybe, CTRL+MouseWheel and leave MouseWheel for scrolling as usual?

**Comment by simonfuhrmann** [comment]
Any news here?

**Comment by keksberg** [comment]
Now zooming is done using CTRL+MouseWheel and the original scrolling behavior remains unaffected. However the code has not been tested under Windows yet. I can also squash the commits into one if this is favored.

**Comment by simonfuhrmann** [comment]
Any updates?

**Comment by simonfuhrmann** [comment]
Any updates?

**Pull request merged**
