### PR TITLE
SFM: Parallelize jacobian computation

### PR DESCRIPTION
**Pull request by nmoehrle**
Split from #313

### CODE REVIEW

**Comment by flanggut** [comment]
I checked the details: The move constructor should be generated by default (see [reference](http://en.cppreference.com/w/cpp/language/move_constructor) ) and if it exists it is also called instead of the copy constructor. So this should be fine as it is.

**Comment by simonfuhrmann** [comment]
It is generated by default under some circumstances, but it is never called for a regular assignment. You need `std::move`. But as already mentioned, since the class contains only primitives, there is really no advantage in moving.

**Comment by flanggut** [comment]
Try this https://gist.github.com/flanggut/f30921d0422ab65d69b955556dc3a81f
For me it says MOVE.

**Comment by simonfuhrmann** [comment]
Ok, you're right. Because it's a temporary.

**Comment by flanggut** [comment]
Should we merge this?

**Comment by simonfuhrmann** [comment]
Your call. If it improves performance and is worth having, merge it! ;-)

**Pull request merged**
