### PR TITLE
Parallel makescene

### PR DESCRIPTION
**Pull request by pierotofy**
Adds support for multi-threaded makescene. It handles photosynth bundle imports by precomputing the camera IDs using a ID --> cameraID dict. Is also declares the num_valid_cams and undist_imported variables as atomic to prevent increment operations from being skipped.

Related to #253

### CODE REVIEW

**Comment by simonfuhrmann** [comment]
Hi there. Thanks for this. Can you squash theses commits into one?

**Comment by pierotofy** [comment]
Sure! Let me know if further changes are required. Thanks! :pray:

**Comment by simonfuhrmann** [comment]
Thanks for the contribution. And sorry for the delay.

**Comment by pierotofy** [comment]
No worries, thanks for reviewing these changes!

**Pull request merged**
