### PR TITLE
Use sRGB linear ramp threshold of implemented standard #256

### PR DESCRIPTION
**Pull request by nmoehrle**

### CODE REVIEW

**Comment by nmoehrle** [comment]
We have a test for sRGB gamma correction [here](https://github.com/simonfuhrmann/mve/blob/master/tests/mve/gtest_image_tools.cc#L369). Should I add a test with some "gold" values or a tests that is checking the threshold and fails before this commit?

**Comment by simonfuhrmann** [comment]
Yes, please add some golden values and epsilon-compare with them. It makes sure we don't break the implementation of the standard. The question is, where do we get reliable golden values from.

**Comment by simonfuhrmann** [comment]
Updates?

**Comment by nmoehrle** [comment]
I could not find any listing of gold values for sRGB conversions. Other library developers such as Nathaniel Smith have created their own set of [gold values](https://github.com/njsmith/colorspacious/blob/master/colorspacious/gold_values.py) based on the color conversion calculators of [http://www.brucelindbloom.com](http://www.brucelindbloom.com/index.html?ColorCalculator.html) and other sites.
So I guess we will have choose a trustworthy converter and generate some ourselves. I would personally vote for Nathaniels [colorspacious](https://github.com/njsmith/colorspacious).

**Comment by simonfuhrmann** [comment]
SGTM

**Pull request merged**
